/**
   * @author Script47 (https://github.com/Script47/Modal)
   * @description Modal - A Bootstrap 4.2+ jQuery plugin for the modal component
   * @version 0.0.1
   **/
(function(g){g.modal=function(a){var b="",h="modal-"+(g("modal").length+1),d=a.title,k="",l="",m="",e=a.content,f=a.buttons||[],n="modal-"+a.size||"",p="undefined"===typeof a.backdrop?!0:a.backdrop,q="undefined"===typeof a.keyboard?!0:a.keyboard,r="undefined"===typeof a.focus?!0:a.focus;switch(a.type||"info"){case "info":k="undefined"!==typeof a.title?"bg-info border-info text-white":"";l="undefined"===typeof e&&0===f.length?"bg-info border-info":"border-info";m="undefined"===typeof d&&"undefined"!==
typeof e?"bg-info text-white":"";break;case "success":k="undefined"!==typeof a.title?"bg-success border-success text-white":"";l="undefined"===typeof e&&0===f.length?"bg-success border-success":"border-success";m="undefined"===typeof d&&"undefined"!==typeof e?"bg-success text-white":"";break;case "warning":case "warn":k="undefined"!==typeof a.title?"bg-warning border-warning text-white":"";l="undefined"===typeof e&&0===f.length?"bg-warning border-warning":"border-warning";m="undefined"===typeof d&&
"undefined"!==typeof e?"bg-warning text-white":"";break;case "error":case "danger":k="undefined"!==typeof a.title?"bg-danger border-danger text-white":"",l="undefined"===typeof e&&0===f.length?"bg-danger border-danger":"border-danger",m="undefined"===typeof d&&"undefined"!==typeof e?"bg-danger text-white":""}b+='<div class="modal fade" id="'+h+'" tabindex="-1" role="dialog" aria-labelledby="'+h+'-title" aria-hidden="false">';b+='<div class="modal-dialog modal-dialog-centered '+n+'" role="document">';
b+='<div class="modal-content '+l+'">';"undefined"!==typeof d&&(b+='<div class="modal-header '+k+'">',b+='<h5 class="modal-title" id="'+h+'-title">'+d+"</h5>",b+='<button type="button" class="close" data-dismiss="modal" aria-label="Close">',b+='<span aria-hidden="true">&times;</span>',b+="</button>",b+="</div>");"undefined"!==typeof e&&(b+='<div class="modal-body '+m+'">',b+=e,b+="</div>");if(0<f.length){b+='<div class="modal-footer">';for(a=0;a<f.length;a++){var c=f[a];d=c.id||h+"-"+c.type+"-"+a;
switch(c.type){case "dismiss":b+='<button type="button" id="'+d+'" class="'+(c["class"]||"btn btn-secondary")+'" data-dismiss="modal">'+c.label+"</button>";break;case "toggle":b+='<button type="button" id="'+d+'" class="'+(c["class"]||"btn btn-secondary")+'" data-toggle="'+c.toggle+'" data-target="'+c.target+'">'+c.label+"</button>";break;default:c.type=c.type||"button",c.id=c.id||d,c["class"]=c["class"]||"btn btn-primary",b+="<button ",Object.keys(c).forEach(function(a){-1===["callback","label"].indexOf(a)&&
(b+=a+'="'+c[a]+'"')}),b+=">"+c.label+"</button>"}if(c.hasOwnProperty("callback"))g(document).on("click","#"+d,c.callback)}b+="</div>"}b+="</div>";b+="</div>";b+="</div>";g("body").append(b);g("#"+h).modal({backdrop:p,keyboard:q,focus:r,show:!0});g("#"+h).on("hidden.bs.modal",function(a){if(0<f.length)for(a=0;a<f.length;a++){var b=f[a],c=b.id||h+"-"+b.type+"-"+a;b.hasOwnProperty("callback")&&g(document).off("click","#"+c)}g(this).remove()});return g("#"+h)}})(jQuery);
